// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"time"
)

type Register struct {
	ID        int64     `json:"id"`
	TeacherID int64     `json:"teacher_id"`
	StudentID int64     `json:"student_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Student struct {
	ID          int64     `json:"id"`
	FullName    string    `json:"full_name"`
	Email       string    `json:"email"`
	IsSuspended bool      `json:"is_suspended"`
	IsActive    bool      `json:"is_active"`
	SuspendedAt time.Time `json:"suspended_at"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	DeletedAt   time.Time `json:"deleted_at"`
}

type Teacher struct {
	ID        int64     `json:"id"`
	FullName  string    `json:"full_name"`
	Email     string    `json:"email"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	DeletedAt time.Time `json:"deleted_at"`
}
