// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"context"
)

type Querier interface {
	CreateRegister(ctx context.Context, arg CreateRegisterParams) error
	CreateStudent(ctx context.Context, arg CreateStudentParams) error
	CreateTeacher(ctx context.Context, arg CreateTeacherParams) error
	GetCommonStudentsEmail(ctx context.Context, arg GetCommonStudentsEmailParams) ([]string, error)
	GetNotSuspendedStudentByEmail(ctx context.Context, email string) (Student, error)
	GetRegisterByStudentId(ctx context.Context, studentID int64) ([]Register, error)
	GetRegisterByStudentIdAndTeacherId(ctx context.Context, arg GetRegisterByStudentIdAndTeacherIdParams) (Register, error)
	GetRegisterByTeacherId(ctx context.Context, teacherID int64) ([]Register, error)
	GetStudentByEmail(ctx context.Context, email string) (Student, error)
	GetStudentById(ctx context.Context, id int64) (Student, error)
	GetStudentsEmailForNotification(ctx context.Context, arg GetStudentsEmailForNotificationParams) ([]string, error)
	GetTeacherByEmail(ctx context.Context, email string) (Teacher, error)
	GetTeacherById(ctx context.Context, id int64) (Teacher, error)
	SuspendStudentByEmail(ctx context.Context, email string) error
}

var _ Querier = (*Queries)(nil)
